"""
COMP 1510 - Yahtzee
Nicholas Johnston
A01242666
December 4, 2020
"""
import io
from unittest import TestCase
import unittest.mock

from yahtzee import scorecard_format


class TestScorecardFormat(TestCase):

    @unittest.mock.patch('sys.stdout', new_callable=io.StringIO)
    def test_scorecard_format_no_score_player_one(self, mock_stdout):
        scorecard_format(f"Player One Scorecard:\n"
                         f"Upper:\n"
                         f"\t1's:\t\n"
                         f"\t2's:\t\n"
                         f"\t3's:\t\n"
                         f"\t4's:\t\n"
                         f"\t5's:\t\n"
                         f"\t6's:\t\n"
                         f"Total Score:\t\n"
                         f"Bonus:\t\n"
                         f"Total of Upper Section:\t\n"
                         f"\nLower:\n"
                         f"\t3 of a Kind:\t\n"
                         f"\t4 of a Kind:\t\n"
                         f"\tFull House:\t\n"
                         f"\tSmall Straight:\t\n"
                         f"\tLarge Straight:\t\n"
                         f"\tYahtzee:\t\n"
                         f"\tChance:\t\n"
                         f"Total Score:\t\n"
                         f"Bonus:\t\n"
                         f"Total of Upper Section:\t\n"
                         f"Total of Lower Section:\t\n"
                         f"Grand Total:\t\n"
                         )
        expected = (f"Player One Scorecard:\n"
                    f"Upper:\n"
                    f"\t1's:\t\n"
                    f"\t2's:\t\n"
                    f"\t3's:\t\n"
                    f"\t4's:\t\n"
                    f"\t5's:\t\n"
                    f"\t6's:\t\n"
                    f"Total Score:\t\n"
                    f"Bonus:\t\n"
                    f"Total of Upper Section:\t\n"
                    f"\nLower:\n"
                    f"\t3 of a Kind:\t\n"
                    f"\t4 of a Kind:\t\n"
                    f"\tFull House:\t\n"
                    f"\tSmall Straight:\t\n"
                    f"\tLarge Straight:\t\n"
                    f"\tYahtzee:\t\n"
                    f"\tChance:\t\n"
                    f"Total Score:\t\n"
                    f"Bonus:\t\n"
                    f"Total of Upper Section:\t\n"
                    f"Total of Lower Section:\t\n"
                    f"Grand Total:\t\n")

        self.assertEqual(mock_stdout.getvalue(), expected)

    @unittest.mock.patch('sys.stdout', new_callable=io.StringIO)
    def test_scorecard_format_no_score_player_two(self, mock_stdout):
        scorecard_format(f"Player Two Scorecard:\n"
                         f"Upper:\n"
                         f"\t1's:\t\n"
                         f"\t2's:\t\n"
                         f"\t3's:\t\n"
                         f"\t4's:\t\n"
                         f"\t5's:\t\n"
                         f"\t6's:\t\n"
                         f"Total Score:\t\n"
                         f"Bonus:\t\n"
                         f"Total of Upper Section:\t\n"
                         f"\nLower:\n"
                         f"\t3 of a Kind:\t\n"
                         f"\t4 of a Kind:\t\n"
                         f"\tFull House:\t\n"
                         f"\tSmall Straight:\t\n"
                         f"\tLarge Straight:\t\n"
                         f"\tYahtzee:\t\n"
                         f"\tChance:\t\n"
                         f"Total Score:\t\n"
                         f"Bonus:\t\n"
                         f"Total of Upper Section:\t\n"
                         f"Total of Lower Section:\t\n"
                         f"Grand Total:\t\n"
                         )
        expected = (f"Player Two Scorecard:\n"
                    f"Upper:\n"
                    f"\t1's:\t\n"
                    f"\t2's:\t\n"
                    f"\t3's:\t\n"
                    f"\t4's:\t\n"
                    f"\t5's:\t\n"
                    f"\t6's:\t\n"
                    f"Total Score:\t\n"
                    f"Bonus:\t\n"
                    f"Total of Upper Section:\t\n"
                    f"\nLower:\n"
                    f"\t3 of a Kind:\t\n"
                    f"\t4 of a Kind:\t\n"
                    f"\tFull House:\t\n"
                    f"\tSmall Straight:\t\n"
                    f"\tLarge Straight:\t\n"
                    f"\tYahtzee:\t\n"
                    f"\tChance:\t\n"
                    f"Total Score:\t\n"
                    f"Bonus:\t\n"
                    f"Total of Upper Section:\t\n"
                    f"Total of Lower Section:\t\n"
                    f"Grand Total:\t\n")

        self.assertEqual(mock_stdout.getvalue(), expected)

    @unittest.mock.patch('sys.stdout', new_callable=io.StringIO)
    def test_scorecard_format_no_two_three_four_score_player_one(self, mock_stdout):
        scorecard_format(f"Player One Scorecard:\n"
                         f"Upper:\n"
                         f"\t1's:\t\n"
                         f"\t5's:\t\n"
                         f"\t6's:\t\n"
                         f"Total Score:\t\n"
                         f"Bonus:\t\n"
                         f"Total of Upper Section:\t\n"
                         f"\nLower:\n"
                         f"\t3 of a Kind:\t\n"
                         f"\t4 of a Kind:\t\n"
                         f"\tFull House:\t\n"
                         f"\tSmall Straight:\t\n"
                         f"\tLarge Straight:\t\n"
                         f"\tYahtzee:\t\n"
                         f"\tChance:\t\n"
                         f"Total Score:\t\n"
                         f"Bonus:\t\n"
                         f"Total of Upper Section:\t\n"
                         f"Total of Lower Section:\t\n"
                         f"Grand Total:\t\n"
                         )
        expected = (f"Player One Scorecard:\n"
                    f"Upper:\n"
                    f"\t1's:\t\n"
                    f"\t5's:\t\n"
                    f"\t6's:\t\n"
                    f"Total Score:\t\n"
                    f"Bonus:\t\n"
                    f"Total of Upper Section:\t\n"
                    f"\nLower:\n"
                    f"\t3 of a Kind:\t\n"
                    f"\t4 of a Kind:\t\n"
                    f"\tFull House:\t\n"
                    f"\tSmall Straight:\t\n"
                    f"\tLarge Straight:\t\n"
                    f"\tYahtzee:\t\n"
                    f"\tChance:\t\n"
                    f"Total Score:\t\n"
                    f"Bonus:\t\n"
                    f"Total of Upper Section:\t\n"
                    f"Total of Lower Section:\t\n"
                    f"Grand Total:\t\n")

        self.assertEqual(mock_stdout.getvalue(), expected)

    @unittest.mock.patch('sys.stdout', new_callable=io.StringIO)
    def test_scorecard_format_no_two_three_four_score_player_two(self, mock_stdout):
        scorecard_format(f"Player Two Scorecard:\n"
                         f"Upper:\n"
                         f"\t1's:\t\n"
                         f"\t5's:\t\n"
                         f"\t6's:\t\n"
                         f"Total Score:\t\n"
                         f"Bonus:\t\n"
                         f"Total of Upper Section:\t\n"
                         f"\nLower:\n"
                         f"\t3 of a Kind:\t\n"
                         f"\t4 of a Kind:\t\n"
                         f"\tFull House:\t\n"
                         f"\tSmall Straight:\t\n"
                         f"\tLarge Straight:\t\n"
                         f"\tYahtzee:\t\n"
                         f"\tChance:\t\n"
                         f"Total Score:\t\n"
                         f"Bonus:\t\n"
                         f"Total of Upper Section:\t\n"
                         f"Total of Lower Section:\t\n"
                         f"Grand Total:\t\n"
                         )
        expected = (f"Player Two Scorecard:\n"
                    f"Upper:\n"
                    f"\t1's:\t\n"
                    f"\t5's:\t\n"
                    f"\t6's:\t\n"
                    f"Total Score:\t\n"
                    f"Bonus:\t\n"
                    f"Total of Upper Section:\t\n"
                    f"\nLower:\n"
                    f"\t3 of a Kind:\t\n"
                    f"\t4 of a Kind:\t\n"
                    f"\tFull House:\t\n"
                    f"\tSmall Straight:\t\n"
                    f"\tLarge Straight:\t\n"
                    f"\tYahtzee:\t\n"
                    f"\tChance:\t\n"
                    f"Total Score:\t\n"
                    f"Bonus:\t\n"
                    f"Total of Upper Section:\t\n"
                    f"Total of Lower Section:\t\n"
                    f"Grand Total:\t\n")

        self.assertEqual(mock_stdout.getvalue(), expected)

    @unittest.mock.patch('sys.stdout', new_callable=io.StringIO)
    def test_scorecard_format_no_upper_player_one(self, mock_stdout):
        scorecard_format(f"Player One Scorecard:\n"
                         f"Upper:\n"
                         f"\t1's:\t\n"
                         f"\t2's:\t\n"
                         f"\t3's:\t\n"
                         f"\t4's:\t\n"
                         f"\t5's:\t\n"
                         f"\t6's:\t\n"
                         f"Total Score:\t\n"
                         f"Bonus:\t\n"
                         f"Total of Upper Section:\t\n"
                         f"\nLower:\n"
                         f"\t3 of a Kind:\t\n"
                         f"\t4 of a Kind:\t\n"
                         f"\tFull House:\t\n"
                         f"\tSmall Straight:\t\n"
                         f"\tLarge Straight:\t\n"
                         f"\tYahtzee:\t\n"
                         f"\tChance:\t\n"
                         f"Total Score:\t\n"
                         f"Bonus:\t\n"
                         f"Total of Upper Section:\t\n"
                         f"Total of Lower Section:\t\n"
                         f"Grand Total:\t\n"
                         )
        expected = (f"Player One Scorecard:\n"
                    f"Upper:\n"
                    f"\t1's:\t\n"
                    f"\t2's:\t\n"
                    f"\t3's:\t\n"
                    f"\t4's:\t\n"
                    f"\t5's:\t\n"
                    f"\t6's:\t\n"
                    f"Total Score:\t\n"
                    f"Bonus:\t\n"
                    f"Total of Upper Section:\t\n"
                    f"\nLower:\n"
                    f"\t3 of a Kind:\t\n"
                    f"\t4 of a Kind:\t\n"
                    f"\tFull House:\t\n"
                    f"\tSmall Straight:\t\n"
                    f"\tLarge Straight:\t\n"
                    f"\tYahtzee:\t\n"
                    f"\tChance:\t\n"
                    f"Total Score:\t\n"
                    f"Bonus:\t\n"
                    f"Total of Upper Section:\t\n"
                    f"Total of Lower Section:\t\n"
                    f"Grand Total:\t\n")

        self.assertEqual(mock_stdout.getvalue(), expected)
